// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHpOA4XpiOgmwiGPkpzDNgczK02LNJLg',
    appId: '1:652658334430:web:c9e62a45f1448d7ad6404f',
    messagingSenderId: '652658334430',
    projectId: 'mijo-5cf09',
    authDomain: 'mijo-5cf09.firebaseapp.com',
    storageBucket: 'mijo-5cf09.appspot.com',
    measurementId: 'G-1QBYVVCQ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylFmOC5k70_zuo3jgzGx-NLxv490tAOw',
    appId: '1:652658334430:android:1052cb89667592b4d6404f',
    messagingSenderId: '652658334430',
    projectId: 'mijo-5cf09',
    storageBucket: 'mijo-5cf09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOV5ldSixmwFzD-mQ63v1seHF2zW4t0pE',
    appId: '1:652658334430:ios:f8a4633e4bb8e413d6404f',
    messagingSenderId: '652658334430',
    projectId: 'mijo-5cf09',
    storageBucket: 'mijo-5cf09.appspot.com',
    iosClientId: '652658334430-gv3tsu6mpf42mj66j6n1ecevnuc5v8b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mijo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOV5ldSixmwFzD-mQ63v1seHF2zW4t0pE',
    appId: '1:652658334430:ios:cfb576ab57e1bdded6404f',
    messagingSenderId: '652658334430',
    projectId: 'mijo-5cf09',
    storageBucket: 'mijo-5cf09.appspot.com',
    iosClientId: '652658334430-b9uj5vh79bp8rtsm9ulmsftof1l9pud2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mijo.RunnerTests',
  );
}
